import * as THREE from 'three';
import {InputManager} from './input.js';import {AudioEngine} from './audio.js';
const $=s=>document.querySelector(s),canvas=$('#game'),hud=$('#hud'),touch=$('#touch');let scene,camera,renderer,input,audio,net=null,NetworkClass=null,physics=null,me,host=false,players=new Map,remoteInputs=new Map,zone=36,phase=0,zoneTimer=45,weapon=0,health=100,shield=100,lastShot=0,lastSnap=0,last=0;
const W=[{n:'ASSAULT RIFLE',mag:30,rate:105,dmg:18,recoil:.018,spread:.018},{n:'TACTICAL SHOTGUN',mag:6,rate:700,dmg:12,recoil:.055,spread:.1},{n:'BOLT SNIPER',mag:5,rate:1000,dmg:95,recoil:.09,spread:.002}],mag=[30,6,5],reserve=[120,30,20];
function material(c){return new THREE.MeshStandardMaterial({color:c,roughness:.7,metalness:.15})}
function cube(x,y,z,w,h,d,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(c));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m);return m}
function actor(c){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(.7,1.2,.45),material(c));b.castShadow=true;g.add(b);const h=new THREE.Mesh(new THREE.SphereGeometry(.25,12,8),material(0xc69f85));h.position.y=.82;g.add(h);return g}
async function getNetwork(){if(!NetworkClass){const m=await import('./network.js');NetworkClass=m.Network}return new NetworkClass()}
function setupNetwork(){net.on('input',(id,p)=>remoteInputs.set(id,p));net.on('state',applyState);net.on('kill',k=>feed(k.text||'ELIMINATION'));net.on('leave',()=>{if(!host)end('Host Left','The host disconnected. The match has ended.')})}
async function init(){try{scene=new THREE.Scene();scene.background=new THREE.Color(0x060b12);scene.fog=new THREE.Fog(0x060b12,.012,85);camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.05,120);renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(pointer:coarse)').matches?1.25:2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.mapSize.set(1024,1024);scene.add(new THREE.HemisphereLight(0x8aa7cf,0x20160f,1.15));const sun=new THREE.DirectionalLight(0xffffff,2.1);sun.position.set(-20,30,12);sun.castShadow=true;scene.add(sun);cube(0,-.8,0,80,.8,80,0x30363e);for(let i=0;i<30;i++){const x=(Math.random()-.5)*68,z=(Math.random()-.5)*68;if(Math.hypot(x,z)>7)cube(x,1,z,3+Math.random()*3,2+Math.random()*2,2+Math.random()*2,0x3b4652)}for(let x=-32;x<=32;x+=8)cube(x,1.5,-36,5,3,1,0x25313c);const ring=new THREE.Mesh(new THREE.CylinderGeometry(1,1,.1,96),new THREE.MeshBasicMaterial({color:0x2ca8ff,transparent:true,opacity:.08,side:THREE.DoubleSide}));ring.position.y=.06;scene.add(ring);window.ring=ring;input=new InputManager(canvas,touch);audio=new AudioEngine();bind();resize();requestAnimationFrame(loop)}catch(e){console.error('Tactical Arena init failed',e);const s=$('#start');if(s){s.classList.remove('hidden');const p=s.querySelector('small');if(p)p.textContent='Game initialization failed. Refresh and try again.'}}}
function bind(){$('#hostBtn').onclick=async()=>{audio.start();try{net=await getNetwork();setupNetwork();await net.hostRoom();host=true;begin(net.room)}catch(e){alert('Room creation failed: '+e.message)}};$('#joinBtn').onclick=async()=>{audio.start();const r=$('#roomInput').value.trim();if(!/^[a-z0-9]{5}$/i.test(r))return alert('Room must be 5 characters.');try{net=await getNetwork();setupNetwork();await net.joinRoom(r);begin(r.toUpperCase())}catch(e){alert('Join failed: Verify the host code.')}};$('#soloBtn').onclick=()=>{audio.start();host=true;begin('SOLO')};$('#restartBtn').onclick=()=>location.reload();addEventListener('resize',resize)}
function begin(room){$('#start').classList.add('hidden');hud.innerHTML='<div class="hud"><div class="top"><div class="pill">ROOM <b id="room">'+room+'</b> · <span id="count">1</span>/8</div><div class="pill">ALIVE <b id="alive">1</b> · ZONE <b id="zt">45</b></div></div><div class="killfeed" id="feed"></div><div class="cross"></div><div class="damage" id="damage"></div><div class="bottom"><div class="bars">HP <b id="hp">100</b><div class="bar"><i id="hpbar"></i></div>SHIELD <b id="sh">100</b><div class="bar shield"><i id="shbar"></i></div></div><div class="ammo"><span id="wn">ASSAULT RIFLE</span><br><b id="am">30 / 120</b></div></div></div>';me={id:host?'host':net.peer.id,mesh:actor(0x4c79d8),pos:new THREE.Vector3(0,1,25),hp:100,alive:true,yaw:0};players.clear();players.set(me.id,me);scene.add(me.mesh);last=performance.now()}
function applyState(s){if(host)return;zone=s.z;phase=s.ph;zoneTimer=s.t;for(const p of s.p){if(p.id===me.id){health=p.hp;shield=p.sh;continue}let q=players.get(p.id);if(!q){q={id:p.id,mesh:actor(0xe07171),pos:new THREE.Vector3(p.x,p.y,p.z),target:new THREE.Vector3(p.x,p.y,p.z),yaw:p.yaw,hp:p.hp,alive:p.a};players.set(p.id,q);scene.add(q.mesh)}q.target.set(p.x,p.y,p.z);q.yaw=p.yaw;q.hp=p.hp;q.alive=p.a;q.mesh.visible=q.alive}}
function move(q,p,dt){if(!q.alive)return;const len=Math.hypot(p.moveX,p.moveY);if(!len){q.yaw=p.yaw;return}const d=new THREE.Vector3(p.moveX,0,p.moveY).normalize().applyAxisAngle(new THREE.Vector3(0,1,0),p.yaw);const speed=p.crouch?2.2:(len>.8?8:5.5);q.pos.addScaledVector(d,speed*dt);q.pos.x=THREE.MathUtils.clamp(q.pos.x,-37,37);q.pos.z=THREE.MathUtils.clamp(q.pos.z,-37,37);q.yaw=p.yaw;q.mesh.position.copy(q.pos);q.mesh.rotation.y=q.yaw;if(q===me&&physics)physics.setPosition(q.pos.x,q.pos.y,q.pos.z)}
function shoot(q,p){const w=W[weapon];if(!p.fire||mag[weapon]<=0||performance.now()-lastShot<w.rate)return;mag[weapon]--;lastShot=performance.now();audio.shot(weapon===1?'shotgun':weapon===2?'sniper':'rifle');p.pitch=THREE.MathUtils.clamp(p.pitch-w.recoil,-1.45,1.45);const dir=new THREE.Vector3(0,0,-1).applyEuler(new THREE.Euler(p.pitch,p.yaw,0,'YXZ')).normalize();const origin=q.pos.clone().add(new THREE.Vector3(0,.5,0)),end=origin.clone().addScaledVector(dir,35),geo=new THREE.BufferGeometry().setFromPoints([origin,end]),line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:weapon===1?0xffc857:0x5fe7ff}));scene.add(line);setTimeout(()=>{scene.remove(line);geo.dispose()},60)}
function frame(dt){const p=input.sample();weapon=p.weapon;if(!me)return;if(host){move(me,p,dt);for(const [id,v] of remoteInputs){let q=players.get(id);if(!q){q={id,mesh:actor(0xe07171),pos:new THREE.Vector3((Math.random()-.5)*30,1,(Math.random()-.5)*30),hp:100,alive:true,yaw:0};players.set(id,q);scene.add(q.mesh)}move(q,v,dt)}}else{net.sendInput(p);move(me,p,dt)}camera.position.copy(me.pos);camera.position.y+=p.crouch?0:.45;camera.rotation.order='YXZ';camera.rotation.y=p.yaw;camera.rotation.x=p.pitch;shoot(me,p);if(p.reload){const w=W[weapon];if(mag[weapon]<w.mag&&reserve[weapon]>0){const n=Math.min(w.mag-mag[weapon],reserve[weapon]);mag[weapon]+=n;reserve[weapon]-=n;audio.reload()}}if(host){zoneTimer-=dt;if(zoneTimer<=0){phase=Math.min(2,phase+1);zone=[36,18,6][phase];zoneTimer=45;audio.zone()}if(Math.hypot(me.pos.x,me.pos.z)>zone)health=Math.max(0,health-dt*8);if(health<=0)me.alive=false;if(net&&performance.now()-lastSnap>50){net.broadcastState({p:[...players].map(([id,q])=>({id,x:+q.pos.x.toFixed(2),y:+q.pos.y.toFixed(2),z:+q.pos.z.toFixed(2),yaw:+q.yaw.toFixed(3),hp:q.hp,sh:100,a:q.alive})),z:zone,ph:phase,t:Math.ceil(zoneTimer)});lastSnap=performance.now()}}else if(me.target)me.pos.lerp(me.target,.15);window.ring.scale.set(zone,zone,zone);if(physics)physics.step(Math.min(dt,.033));updateHud()}
function updateHud(){$('#hp')?.replaceChildren(Math.ceil(health));$('#sh')?.replaceChildren(Math.ceil(shield));if($('#hpbar'))$('#hpbar').style.width=Math.max(0,health)+'%';if($('#shbar'))$('#shbar').style.width=Math.max(0,shield)+'%';if($('#am'))$('#am').textContent=mag[weapon]+' / '+reserve[weapon];if($('#wn'))$('#wn').textContent=W[weapon].n;if($('#zt'))$('#zt').textContent=Math.max(0,Math.ceil(zoneTimer));if($('#count'))$('#count').textContent=players.size;if($('#alive'))$('#alive').textContent=[...players.values()].filter(p=>p.alive).length}
function feed(t){const f=$('#feed');if(!f)return;const e=document.createElement('div');e.textContent=t;f.prepend(e);setTimeout(()=>e.remove(),3000)}function end(t,x){$('#ended').classList.remove('hidden');$('#endTitle').textContent=t;$('#endText').textContent=x}function resize(){if(!camera||!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}function loop(now){requestAnimationFrame(loop);const dt=Math.min(.033,(now-(last||now))/1000);last=now;if(me)frame(dt);renderer.render(scene,camera)}init();